### ISSUE TITLE
Unable to decode Json

### ISSUE THREAD

**Issue by namelivia** [surplustv/plugin.video.meanstv#44]
First of all, I wanted to thank you, for developing this plugin, I just discovered meants.tv and thought it would be awesome having a Kodi plugin for it, and boom! here it is.

I've attempted to install it and run it and wanted to share my experience in case you may find it helpful from a fresh eyes perspective. First I tried to install by downloading the repository as a ZIP file but it raised an error stating it couldn't read the contents of the zip file.

Anyway, I copied the files over to `~/.kodi/addons` and then activated it, now when running it I get the following trace:

```
2021-03-09 19:11:42.362 T:1900446640 WARNING: Previous line repeats 2 times.
2021-03-09 19:11:42.362 T:1900446640   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2021-03-09 19:11:49.187 T:1763590368   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'simplejson.errors.JSONDecodeError'>
                                            Error Contents: Expecting value: line 1 column 1 (char 0)
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.meanstv/main.py", line 12, in <module>
                                                router.route(sys.argv[2][1:])
                                              File "/home/pi/.kodi/addons/plugin.video.meanstv/resources/lib/router.py", line 45, in route
                                                handler.list_categories()
                                              File "/home/pi/.kodi/addons/plugin.video.meanstv/resources/lib/handler.py", line 159, in list_categories
                                                categories = api.load_categories()
                                              File "/home/pi/.kodi/addons/plugin.video.meanstv/resources/lib/api.py", line 89, in load_categories
                                                json_list = response.json()
                                              File "/home/pi/.kodi/addons/script.module.requests/lib/requests/models.py", line 897, in json
                                                return complexjson.loads(self.text, **kwargs)
                                              File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 518, in loads
                                                return _default_decoder.decode(s)
                                              File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
                                                obj, end = self.raw_decode(s)
                                              File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
                                                return self.scan_once(s, idx=_w(s, idx).end())
                                            JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                            -->End of Python script error report<--
2021-03-09 19:11:49.353 T:1755197664   ERROR: GetDirectory - Error getting plugin://plugin.video.meanstv/
2021-03-09 19:11:49.355 T:1900446640   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.meanstv/) failed
```

I suppose it is crashing because the contents of the response changed, not sure if it is related with #43 
In any case, keep it on! And if you want me to help I'm more than happy, let me know if you want me to help you debug this issue or you are already aware of it.

**Comment by namelivia** [comment]
Nevermind! That was it, I took some time to read through the PR, tested that branch, and was able to play files. Closing it!
Still congrats for your work!

**Comment by czoller** [comment]
Dear José, thanks a lot for feedback. We really appreciate that.
I'm sorry that the PR has not yet been merged to main branch. I will do so now. 
And we will soon submit the plugin to the official Kodi repository, so that the installation will hopefully be more convenient.
